language: go

go:
  - 1.10.x
  - tip

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

go_import_path: gopkg.in/src-d/regression-core.v0

script:
  - make dependencies
  - make test-coverage

