language: go
dist: xenial

go:
  - 1.12.x
  - 1.11.x

env:
  - GO111MODULE=on

go_import_path: github.com/src-d/regression-core

matrix:
  fast_finish: true


script:
  - make dependencies
  - make test-coverage

